apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl
  name: curl
spec:
  containers:
  - image: curlimages/curl
    name: curl
    envFrom:
    - configMapRef:
        name: pln-exchange-rate-ip
    command: ['sh', '-c']
    args:
      - while true; do
          curl -i $PODIP:5000/prevday/exchangerate/usd/2022-01-10;
        done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
