apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pln-exchange-rate
  name: pln-exchange-rate
spec:
  containers:
  - image: mramotow/pln_exchange_rate
    name: pln-exchange-rate
    ports:
    - containerPort: 5000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
