apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
spec:
  containers:
  - image: mramotow/pln_exchange_rate
    name: pln-exchange-rate
    ports:
    - containerPort: 5000
  - image: curlimages/curl
    name: curl
    command: ['sh', '-c']
    args:
      - while true; do
          curl -i localhost:5000/prevday/exchangerate/usd/2022-01-10;
        done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
